<?php
/*
 * @file
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implementing hook_menu();
 */
function fancourier_estimare_menu() {
  $items['admin/config/fancourier'] = array(
    'title' => 'Fancourier Estimare',
    'description' => 'Fancourier Estimare Description',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fancourier_estimare_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'menu_name' => 'management',
    'weight' => -5,
  );
  return $items;
}
/**
 * Implements hook_form($node, &$form_state)
 * @param type $form
 * @param type $form_state
 * @returns the form.
 */
function fancourier_estimare_form($form, &$form_state) {
  
  //Grabbing form adress data options..
  $adrese = get_adress_data_by_nodeid();
  //Grabbing form transport types options..
  $grabbed_enabled_transport_types = get_fancourier_services_enabled(); 
  
  $form['adresses'] = array(
    '#type' => 'select',
    '#title' => 'Adresa Destinatie',
    '#description' => t('translatable description.'),
    '#options' => $adrese,
  );
  
  $form['selected_transport_type'] = array(
    '#type' => 'select',
    '#title' => 'Tip transport:',
    '#description' => t('transalfsdf description'),
    '#options' => $grabbed_enabled_transport_types,
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Estimeaza taxa transport !',   
  );
  return $form;
}
/**
 * EFQ sql querry to return a list of nodes with "adresa" bundle.
 * @return type List of Objects 
 */
function get_adresses_node_object() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'adresa')
  ->propertyCondition('status', 1)
  ->addMetaData('account', user_load(1)); // Run the query as user 1.
  $result = $query->execute();
  
if (isset($result['node'])) {
  $addresses_nids = array_keys($result['node']);
  $addresses_values = array_values($result['node']);
  $addresses_objects = entity_load('node', $addresses_nids);
}
//TEST DELETE TEST
$asd = array();
foreach ($addresses_values as $key => $value ){
  $asdfgh[$key] = $value->nid;
 }
//dpm($asdfgh);
//dpm($addresses_values);
//END TEST (delete) TEST

  //dpm($addresses_objects);
 return $addresses_objects; 
}
/**
 * Function to grab nodes , and node's data
 * @return type array of node id's from the node.
 */
function get_adress_data_by_nodeid() {
  $objects = get_adresses_node_object();
  foreach ($objects as $key => $value) {
    $nodeid_array[] = $value->nid;
  }
  $query = db_select('field_data_field_addressfield', 'addressfield')
    ->fields('addressfield')
    ->condition('entity_id', $nodeid_array)
    ->orderBy('field_addressfield_locality', 'DESC')//ORDER BY created
    ->range(0, 500);//LIMIT to 2 records
    $results= $query->execute();
  foreach ($results as $key => $value) {
    $entity_id = $value->entity_id;//dpm($value->field_addressfield_thoroughfare);\
    $city = $value->field_addressfield_locality;
    $strada = $value->field_addressfield_thoroughfare;
    $cod_tara = $value->field_addressfield_country;
    $nume_complet = $value->field_addressfield_name_line;
    //UNCOMMENT TO VIEW COMPLETE DATA    
    //dpm('EntityID : ' . $entity_id . ' Oras: ' . $city . ' Strada: ' . $strada . ' Tara: ' . $cod_tara . ' Nume complet: ' . $nume_complet);
    $adrese[$entity_id] = $strada; // Aici e return-ul pentru select-ul adresei de destinatie
  }
  return $adrese;
}

/**
 * Function that returns an array of the enabled services 
 * (fancourier transport types) within the database.
 * @return type array of items.
 */
function get_fancourier_services_enabled() {
  $fancourier_variable = variable_get('fancourier');
  $services_enabled = $fancourier_variable['services'];
  
  foreach ($services_enabled as $key => $value) {
     $service_enabled[$key] = $value;
  }
  return $service_enabled;
}
/**
 * Implements hook_form_submit();
 * Deocamdata printam valorile celor 2 field-uri...
 * @param type $form
 * @param type $form_state
 */
function fancourier_estimare_form_submit($form, &$form_state) {
  if (isset($form_state['values'])) {
    dpm('exista formstate de values. il printam');
    dpm($form_state['values']);
  }
  else{
    dpm('nu exista form state de values');
  }
 
}
/**
 * Implements hook_form_alter().
 * @param string $form
 * @param type $form_state
 * @param type $form_id
 */
function fancourier_estimare_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'fancourier_form') {
     $form['#submit'][] = 'fancourier_submit_handler';
  }
}
/**
 * Function to redirect after clicking submit
 */
function fancourier_submit_handler(&$form, &$form_state) {
  $form_state['redirect'] = 'admin/config/fancourier';
}
