<?php
/*
 * @file
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implementing hook_menu();
 */
function fancourier_estimare_menu() {
  $items['admin/config/fancourier'] = array(
    'title' => 'Fancourier Estimare',
    'description' => 'Fancourier Estimare Description',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fancourier_estimare_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'menu_name' => 'management',
    'weight' => -5,
  );
  return $items;
}
/**
 * Implements hook_form($node, &$form_state)
 * @param type $form
 * @param type $form_state
 * @returns the form.
 */
function fancourier_estimare_form($form, &$form_state) {
  //Grabbing form adress data options..
  $adrese = get_adress_data_by_nodeid();
  //Grabbing form transport types options..
  $grabbed_enabled_transport_types = get_fancourier_services_enabled(); 
   
  $form['selected_transport_type'] = array(
    '#type' => 'select',
    '#title' => 'Tip transport:',
    '#description' => t('transalfsdf description'),
    '#options' => $grabbed_enabled_transport_types,
  );
  $form['addresses'] = array(
    '#type' => 'select',
    '#title' => 'Adresa Destinatie',
    '#description' => t('translatable description.'),
    '#options' => $adrese,
    '#ajax' => array(
      'callback' => 'fancourier_estimare_taxetransport_callback',
      'wrapper' => 'taxetransport',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );
 
  /////////////////////////////////////////////////////////////////////////////////
  ////////////////////////////////////
  /// Zona in care se va updata pretul
  ////////////////////////////////////////////////////
  $form['transport_taxes'] = array(
    '#title' => t("Taxe Transport"),
    // The prefix/suffix provide the div that we're replacing, named by
    // #ajax['wrapper'] above.
    '#prefix' => '<div id="taxetransport">',
    '#suffix' => '</div>',
    '#type' => 'markup',
    '#markup'=> '',
    '#value' => 'testtext',
    '#description' => t('This is where we get automatically generated transport tax data.'),
  );
  return $form;
}
/**
 * EFQ sql querry to return a list of nodes with "adresa" bundle.
 * @return type List of Objects 
 */
function get_adresses_node_object() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'adresa')
  ->propertyCondition('status', 1)
  ->addMetaData('account', user_load(1)); // Run the query as user 1.
  $result = $query->execute();
  
if (isset($result['node'])) {
  $addresses_nids = array_keys($result['node']);
  $addresses_values = array_values($result['node']);
  $addresses_objects = entity_load('node', $addresses_nids);
}
  //dpm($addresses_objects);
 return $addresses_objects; 
}
/**
 * Function to grab nodes , and node's data
 * @return type array of node id's from the node.
 */
function get_adress_data_by_nodeid() {
  $objects = get_adresses_node_object();
  foreach ($objects as $key => $value) {
    $nodeid_array[] = $value->nid;
  }
  $query = db_select('field_data_field_addressfield', 'addressfield')
    ->fields('addressfield')
    ->condition('entity_id', $nodeid_array)
    ->orderBy('field_addressfield_locality', 'DESC')//ORDER BY created
    ->range(0, 500);//LIMIT to 2 records
    $results= $query->execute();
  foreach ($results as $key => $value) {
    $entity_id = $value->entity_id;//dpm($value->field_addressfield_thoroughfare);\
    $city = $value->field_addressfield_locality;
    $strada = $value->field_addressfield_thoroughfare;
    $cod_tara = $value->field_addressfield_country;
    $nume_complet = $value->field_addressfield_name_line;
    //UNCOMMENT TO VIEW COMPLETE DATA    
    //dpm('EntityID : ' . $entity_id . ' Oras: ' . $city . ' Strada: ' . $strada . ' Tara: ' . $cod_tara . ' Nume complet: ' . $nume_complet);
    //$adrese[$entity_id] = $city; // Aici e return-ul pentru select-ul adresei de destinatie
    $adrese[$city] = $city; // Aici e return-ul pentru select-ul adresei de destinatie
  }
  return $adrese;
}
/**
 * Function that returns an array of the enabled services 
 * (fancourier transport types) within the database.
 * @return type array of items.
 */
function get_fancourier_services_enabled() {
  $fancourier_variable = variable_get('fancourier');
  $services_enabled = $fancourier_variable['services'];
  foreach ($services_enabled as $key => $value) {
     $service_enabled[$key] = $value;
  }
  return $service_enabled;
}
/**
 * Implements hook_form_submit();
 * Deocamdata printam valorile celor 2 field-uri...
 * @param type $form
 * @param type $form_state
 */
function fancourier_estimare_form_submit($form, &$form_state) {
  if (isset($form_state['values'])) {
    //dpm('exista formstate de values. il printam');
    //dpm($form_state['values']);
    
    $DATA_adress_nid = $form_state['values']['adresses'];
    $DATA_transport_type = $form_state['values']['selected_transport_type'];
    dpm("Address node is : " . $DATA_adress_nid);
    dpm("Transporttype is : " . $DATA_transport_type);
    dpm("this data should be used by AJAX to display information about the price");
    
  }
  else{
    dpm('nu exista form state de values');
  }
}
/**
 * Implements hook_form_alter().
 * @param string $form
 * @param type $form_state
 * @param type $form_id
 */
function fancourier_estimare_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'fancourier_form') {
     $form['#submit'][] = 'fancourier_submit_handler';
  }
}
/**
 * Function to redirect after clicking submit
 */
function fancourier_submit_handler(&$form, &$form_state) {
  $form_state['redirect'] = 'admin/config/fancourier';
}

/**
 * Callback function for 
 * @param type $form
 * @param type $form_state
 * @return type
 */
function fancourier_estimare_taxetransport_callback($form, $form_state) {
  //dpm($form_state['values']);
  //dpm($form_state['values']['addresses']);
  //dpm($form_state['values']['selected_transport_type']);
  
  $shipping_service = 'Standard';
  $shipping_service = $form_state['values']['selected_transport_type'];
  $shipping_adress = $form_state['values']['addresses'];
  $shipping_default = array(
    'localitate_dest' => '',
    'judet_dest' => 'Mures',
    'plicuri' => '0',
    'colete' => '1',
    'greutate' => '1',
    'lungime' => '',
    'latime' => '',
    'inaltime' => '',
  );
  $shipping_override = array(
    'localitate_dest' => $shipping_adress,    
  );
  $shipping = array_merge($shipping_default, $shipping_override);
  
  // As long as you're dealing with string keys, array_merge does exactly what you want. 
  //The two arrays are combined, and where the two have the same keys, the values from $second overwrite the values from $first.
  //  
   // Get shipping amount.
  $db_fan_login = variable_get('fancourier', array());
  $fan = new FanCourier($db_fan_login['login']);
  $amount = $fan->estimateShipping($shipping, $shipping_service);
  
  
  $display_frumos = '<h2>Taxa aproximativa : ' . $amount . ' lei </h2>';
  $form['transport_taxes']['#value'] = $amount;
  $form['transport_taxes']['#markup'] = $display_frumos;
  //dpm($form);
  return $form['transport_taxes'];
}


